//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkWell
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apply_tbl
    {
        public int Application_Id { get; set; }
        public int User_Id { get; set; }
        public int Job_Id { get; set; }
        public string Resume { get; set; }
        public string Status { get; set; }
        public string Applied_date { get; set; }
        public int company_Id { get; set; }
    }
}
