//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkWell
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_tbl
    {
        public int Company_Id { get; set; }
        public string CName { get; set; }
        public string CAddress { get; set; }
        public string CPhone { get; set; }
        public string CEmail { get; set; }
    }
}
