//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkWell
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_vacancies_tbl
    {
        public int Job_Id { get; set; }
        public int Company_Id { get; set; }
        public string JobTitle { get; set; }
        public string Description { get; set; }
        public string Experience { get; set; }
        public string Location { get; set; }
        public string Salary { get; set; }
        public string PostedDate { get; set; }
        public string Status { get; set; }
        public string ClosingDate { get; set; }
        public string JType { get; set; }
        public string Skills { get; set; }
    }
}
